# 
# molsim is a (wrapper) class in the molsim-package. 
# It contains all the relevat properties and methods for a simulation. 
# 
# class properties
# - sub-classes: atoms, integrator, thermostat, pairforce, bonds, angels, dihedrals 
# - vectors: lbox 
# - scalars: natoms, nmols, volume, nthreads 
#
# Examples: See package examples/ folder
#
classdef molsim < handle
	
	properties (Access=public)
		# Classes
		atoms;
		
		integrator;  
		thermostat; thermtype;

		pairforce;  
		bonds;
		angles;
		dihedrals;
	
		# Aux. system quantities/properties 	
		natoms;
		lbox; volume;
		#temperature;

		# Molecule info
		nmols; atom_idxs; 

		# No. threads 
		nthreads;
	end

	methods
		
		## Usage: sim = molsim();
		## 
		## Returns an empty instance of molsim class object
		function this = molsim()
			this;	
		end

		## Usage: setconf(configuration-file) 
		##        setconf([nx, ny, nz],[Lx, Ly, Lz], temperature);     
		##
		## Sets system configuration from file or from specified dimensions
		##
		## Example:
		## >> sim = molsim();
		## >> sim.setconf("configuration.xyz");
		## or
		## >> sim = molsim();
		## >> sim.setconf([10, 12, 10], [11, 14, 12], 2.0);
		function setconf(this, fnameOrSize, boxLengths, temperature)	
	
			if nargin==2
				this.atoms = ms_atoms(fnameOrSize); 
			elseif nargin==4
				this.atoms = ms_atoms(fnameOrSize, boxLengths, temperature);
			else
				error("Invalid call to setconf");
			end

			# Auxillary properties (bit of copying)
			this.natoms = this.atoms.natoms; 
			this.lbox = this.atoms.lbox;
			this.volume = prod(this.lbox);

			# Default no. of threads
			this.nthreads = 4;

			# Minimal required sub-classes for a simulatios 
			this.integrator = ms_integrator(); 
			this.pairforce = ms_pairforce(); 
		end

		## Usage: settop(file name)
		##
		## Read topology file generated by the molconf tool
		## 
		## Example:
		## >> molconf("water.xyz", "water.top", [10 10 10], 2.0);  
		## >> sim = molsim(); 
		## >> sim.setconf("configuration.xyz"); 
		## >> sim.settop("topology.mat");
		##
		## See also water.m in examples/
		function settop(this, fname="topology.mat")
		
			if !exist(fname)
				error("Topology file does not exists\n");
			end
	
			load(fname); 
		
			this.nmols = nmols;
			this.atom_idxs = atom_idxs;
	
			# Bonds
			if binfo != -1

				nbonds = rows(binfo); 
				
				this.bonds = ms_bonds(nbonds);
				this.bonds.pidx = binfo(:,1:2) + 1;
				this.bonds.btypes = binfo(:,3);			
			end
			
			# Angles
			if ainfo != -1
				
				nangles = rows(ainfo);
				
				this.angles = ms_angles(nangles);
				this.angles.pidx = ainfo(:,1:3) + 1;
				this.angles.atypes = ainfo(:,4);			
			end 

		
			# Dihedral
			if dinfo != -1
				
				ndihedrals = rows(dinfo);
			
				this.dihedrals = ms_dihedrals(ndihedrals);
				this.dihedrals.pidx = dinfo(:,1:4) + 1;
				this.dihedrals.dtypes = dinfo(:,5);			
			end

		end

		## Usage: scalebox(target density)
		##        scalebox(target density, directions, scale factor)
		##
		## Scales the simulation box with scale factor (if not specifed this defaults to 0.999)
		##
		## Example:
		## >> sim=molsim();
		## >> sim.scalebox(0.98, [1:2], 0.9999);
		function scalebox(this, dens0, dirs=[1:3], prefac=0.999)

			densnow = this.natoms/this.volume;

			if densnow < dens0
				this.lbox(dirs) = prefac*this.lbox(dirs);
			else 
				this.lbox(dirs) = this.lbox(dirs)./prefac;
			end	
			
			this.volume = prod(this.lbox);
			this.atoms.lbox = this.lbox;

			# Ensures neighbourlist rebuild
			this.pairforce.first_call_simulation = true;				
		end

		## Usage: setnthreads(number of threads)
		##
		## Sets the number of threads for parallel computing (by default set to 4)
		##
		## Example:
		## >> sim=molsim();
		## >> sim.setnthreads(4);
		function setnthreads(this, nthreads=4)

			this.nthreads = nthreads;
			ms_setomp(nthreads);

		end

		## Usage addatom(position, atom type, mass, charge)
		##
		## Inserts an atom at a particular position. NOTE: position 
		## should be different from any other atom's position 
		##
		## Example
		## >> sim = molsim();
		## >> sim.setconf([10,10,10],[11, 11, 23], 1.0);
		## >> sim.addatom(rand*sim.lbox, 'B', 2.0, -2.);
		function addatom(this, r, atype, mass, charge)
		
			this.natoms = this.natoms + 1;
			this.atoms.natoms = this.natoms;

			this.atoms.r = [this.atoms.r; r];
			this.atoms.rl = [this.atoms.rl; r];
			this.atoms.r0 = [this.atoms.r0; r];
			this.atoms.v = [this.atoms.v; rand(1,3)];
			this.atoms.f = [this.atoms.f; [0,0,0]];
				
			this.atoms.t = [this.atoms.t; atype(1)];
			this.atoms.m = [this.atoms.m; mass];
			this.atoms.q = [this.atoms.q; charge];

			this.atoms.nblist = [this.atoms.nblist; -1*int32(ones(1, this.atoms.max_nnb))];
			this.atoms.exclude = [this.atoms.exclude; -1*int32(ones(1, this.atoms.max_exclude))];
			this.atoms.bxcrs = [this.atoms.bxcrs; [0,0,0]];
		end


		## Usage: lennardjones(atom types, lj params)
		## 
		## Calculates the Lennard-Jones pair force between particles
		## lj parameters is a 4-vector [cut-off, epsilon, sigma, aw]
		##
		## Example
		## >> sim = molsim();
		## >> sim.setconf([10,10,10],[11, 11, 23], 1.0);
		## >> [epot, Pconf] = sim.lennardjones("AA", [2.5,1.0,1.0,0.0]);
		function [epot Ppot] = lennardjones(this, atypes, params)
			[epot, Ppot] = this.pairforce.lj(this.atoms, atypes, params);		
		end

		## Usage: sfcoulomb(cutoff)
		##
		## Calculates the Coulomb interactions using a shifted force method
		## See e.g. Hansen et al., J. Phys. Chem. B, 5738:116 (2012) 
		##
		## Example: see water.m 
		function [epot Ppot] = sfcoulomb(this, cutoff)
			[epot, Ppot] = this.pairforce.sf(this.atoms, cutoff);
		end

 		## Usage: ljcsf(atom types, params)
		## 
		## Calculates the Lennard-Jones and Coulomb pair force between particles.
		## params is a 5-vector [LJ cut-off, epsilon, sigma, aw, Coulomb cut-off]
		## Faster than calling lennardjones and sfcoulomb separately 
		##
		## Example
		## >> sim = molsim();
		## >> sim.setconf([10,10,10],[11, 11, 23], 1.0);
		## >> sim.pairforce.max_cutoff = 3.5;
		## >> [epot, Pconf] = sim.ljcsf("AA", [2.5,1.0,1.0,0.0, 3.5]);
		function [epot Ppot] = ljcsf(this, atypes, params)
			[epot, Ppot] = this.pairforce.ljcsf(this.atoms, atypes, params);
		end
 
		## Usage: harmonicbond(bond type)
		##
		## Calculates the bond forces using a harmonic bond potential
		##
		## Example: see butane.m
		function epot = harmonicbond(this, btype)
			epot = this.bonds.harmonic(this.atoms, btype);
		end

		## Usage: harmonicangle(angle type)
		##
		## Calculates the angle forces using a harmonic angle potential
		##
		## Example: see butane.m
		function epot = harmonicangle(this, atype)
			epot = this.angles.harmonic(this.atoms, atype);
		end

		## Usage: ryckbell(dihed. type)
		## 
		## The Ryckaert-Bellemann dihedral model
		##
		## Example: see butane.m
		function epot = ryckbell(this, dtype)
			epot = this.dihedrals.ryckbell(this.atoms, dtype);
		end

		## Usage: leapfrog()
		##
		## Integrate forward one step using the leap-frog algorithm
		##
		## Example: see lj.m
		function [ekin Pkin] = leapfrog(this)
			[ekin, Pkin] = this.integrator.lf(this.atoms, this.pairforce);
		end

		## Usage: setthermostat(thermostate type, atom types, temperatures, relax times)
		##        setthermostat(thermostate type, temperature, relax time)
		##
		## Defines/sets the thermostat device. Possible types are "nh" (Nose-Hoover) and "relax"
		## (simple temperature relaxation). For "nh" relaxation time should be in order of 10, for
		## "relax" the relaxation time should be in order of 0.1-0.01.
		##
		## IMPORTANT: When applying the Noose-Hoover thermostat on specific types the overall
		## momentum is not conserved. Can be enforced by the user through the resetmom method. 
		##
		## Example
		## >> # Thermostat type A and B to temperature 1 and 2 respectively using relaxation device  
		## >> sim.setthermostat("relax", "AB", [1.0, 2.0], [0.01, 0.01]);
		## >> # Thermostat all system particles with a Nose-Hoover to temperaure 1.42
		## >> sim.setthermostat("nh", 1.42, 10.0);   
		function setthermostat(this, thermtype, atomtypesOrTemperature, temperaturesOrTauQ, tauQ)
	
			this.thermtype = thermtype;

			if nargin==4
				this.thermostat = ms_thermostat(atomtypesOrTemperature, temperaturesOrTauQ); 
			elseif nargin==5
				this.thermostat = ms_thermostat(atomtypesOrTemperature, tauQ, temperaturesOrTauQ);
			else
				error("setthermostat requires 3 or 4 arguments");
			end

		end 

		## Usage: applythermostat()
		##
		## Apply the thermostat set by the setthermostat method.
		##
		## Example: See butane.m
		function applythermostat(this)

			if strcmp(this.thermtype, "nh")
				this.thermostat.nosehoover(this.atoms, this.integrator.dt);
			elseif strcmp(this.thermtype, "relax") 
 				this.thermostat.relaxtemp(this.atoms);
			end
		end
		
		## Usage: [rmol masses] = getmolpos()
		##
		## Get molecular centre of masses and molecular masses
		##
		## Example:
		## >> molconf("butane.xyz", "butane.top", [5 5 20], 3.0);
		## >> sim = molsim();
		## >> sim.setconf("start.xyz"); sim.settop();
		## >> sim.getmolpos()
		function [rmols mmols] = getmolpos(this)
			nuau = columns(this.atom_idxs);
			[rmols mmols] = ms_calcmolpos(this.atoms.r, this.atoms.m, nuau*this.nmols, ...
											this.atom_idxs, nuau, this.lbox); 


		end
		
		## Usage: vmol = getmolvel()
		##
		## Get molecular centre of velocity
		##
		## Example:
		## >> molconf("butane.xyz", "butane.top", [5 5 20], 3.0);
		## >> sim = molsim();
		## >> sim.setconf("start.xyz"); sim.settop();
		## >> sim.getmolvel()
		function vmols = getmolvel(this)
			nuau = columns(this.atom_idxs);
			vmols = ms_calcmolvel(this.atoms.v, this.atoms.m, nuau*this.nmols, this.atom_idxs, nuau); 
		end
	
		## Usage: ete = getmolete()
		##
		## Get molecular centre of velocity
		##
		## Example:
		## >> molconf("butane.xyz", "butane.top", [5 5 20], 3.0);
		## >> sim = molsim();
		## >> sim.setconf("start.xyz"); sim.settop();
		## >> sim.getmolete()
		function ete = getmolete(this)
			nuau = columns(this.atom_idxs);
			ete = ms_calcmolete(this.atoms.r, this.nmols*nuau, this.atom_idxs, nuau, this.lbox);
		end

	end

end

